spring:
  application:
      name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/fassciodb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password:
    password: ENC(dmIRdpSRscZCQvOiTTNN49UR3SWKSgjaOMfwyY02k81+RK1C3EQmQ3FR4Gc65EvQ)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
orderException:
  exceptionItem: Item Out Of Stock
  exceptionBalance: Insufficient Balance
  exceptionUser: Error While Fetching The User Orders
  exceptionOrder: Order Not Found
  exceptionInactive: Order Is Inactive
  exceptionFetching: Error While Fetching User Transaction
  exceptionValue: Required request body is missing